# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNP', '0004_remove_snp_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='snp',
            name='reference',
            field=models.CharField(default='NONE', max_length=255),
        ),
    ]
