# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-11 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SNP', '0006_auto_20160510_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snp',
            name='functional_snps',
        ),
        migrations.RemoveField(
            model_name='snp',
            name='tag_snps',
        ),
        migrations.AddField(
            model_name='snp',
            name='chrom',
            field=models.CharField(default='chrom', max_length=255),
        ),
        migrations.AddField(
            model_name='snp',
            name='chrom_start_end',
            field=models.CharField(default='chrom:start-end', max_length=255),
        ),
        migrations.AddField(
            model_name='snp',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snp',
            name='rsid',
            field=models.CharField(default='rsid', max_length=255),
        ),
        migrations.AddField(
            model_name='snp',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='snp',
            name='type_snps',
            field=models.CharField(choices=[('functional', 'Functional'), ('tag', 'Tag')], default='type', max_length=255),
        ),
        migrations.AlterField(
            model_name='snp',
            name='trait',
            field=models.CharField(default='trait', max_length=255),
        ),
    ]
